[package]
name = "baptized_ui"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/baptized_ui.rs"

[dependencies]
editor.workspace = true
gpui.workspace = true
paths.workspace = true
ui.workspace = true
workspace.workspace = true
